/**
 * @ngdoc overview
 * @name <%= config.get('name') %>-demo
 *
 * @description
 * Generated by Yo men
 *
 * **Note:** A demo application meant to display the module's api
 *
 * @example
  http://localhost:8000
 */

angular.module('<%= config.get("name") %>-demo', [ '<%= config.get("name") %>', 'ngRoute' ])
.config([ '$routeProvider', '$locationProvider', function($routeProvider,$locationProvider) {

    $routeProvider
      .when('/', {
        templateUrl: 'demo/main.html',
        controller: 'demoCtrl'
      })
      .otherwise({
        redirectTo: '/'
      });

    $locationProvider.html5Mode(true);

}]).run([ '$rootScope', '$location', function($rootScope,$location) {
  $rootScope.isActive = function (href) {
    return href === $location.path();
  };
}]);
