/**
 * @ngdoc overview
 * @name <%= config.get('name') %>
 *
 * @description
 * Generated by Yo men
 *
 * **Note:** This is a headless module. It provides routes, services and directives to applications. The index.html in this project is just a demo app to demo the module's exports.
 *
 */

angular.module('<%= config.get("name") %>', [ <%
  if (config.get('uxFramework') === 'material') {
%>'ngMaterial', <%
  } else {

  }
%>
'ngRoute'
]);
